sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-ycp-ui-bindings-image .
script:
  # the "yast-travis-cpp" script is included in the base yastdevel/cpp image
  # see https://github.com/yast/docker-yast-cpp/blob/master/yast-travis-cpp
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-ycp-ui-bindings-image yast-travis-cpp

after_success:
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e SURGE_LOGIN="$SURGE_LOGIN" -e SURGE_TOKEN="$SURGE_TOKEN" yast-ycp-ui-bindings-image /bin/bash -c "zypper  in -y npm doxygen; npm install --global surge; rake doc; surge --project ./autodoc/html --domain yast-ui-bindings.surge.sh"
